// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace InfinityMatrix.Niraiya.UITests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("04_StaticScreens", Description=@"![04_StaticScreens]
Link to a feature: [StaticScreens](InfinityMatrix.Niraiya.UITests/Features/04_StaticScreens.feature)
***Further read***: **[Learn more about how to generate Living Documentation](https://docs.specflow.org/projects/specflow-livingdoc/en/latest/LivingDocGenerator/Generating-Documentation.html)**", SourceFile="Features\\04_StaticScreens.feature", SourceLine=0)]
    public partial class _04_StaticScreensFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "04_StaticScreens.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "04_StaticScreens", @"![04_StaticScreens]
Link to a feature: [StaticScreens](InfinityMatrix.Niraiya.UITests/Features/04_StaticScreens.feature)
***Further read***: **[Learn more about how to generate Living Documentation](https://docs.specflow.org/projects/specflow-livingdoc/en/latest/LivingDocGenerator/Generating-Documentation.html)**", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void _04_10NavigateToStaticPages(string environment, string browser, string device, string scenarioName, string pageURL_AppSettings, string millisecond, string pageLoadedInSeconds, string pageScrollStep, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "StaticScreens",
                    "Parallel"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Environment", environment);
            argumentsOfScenario.Add("Browser", browser);
            argumentsOfScenario.Add("Device", device);
            argumentsOfScenario.Add("ScenarioName", scenarioName);
            argumentsOfScenario.Add("PageURL-AppSettings", pageURL_AppSettings);
            argumentsOfScenario.Add("Millisecond", millisecond);
            argumentsOfScenario.Add("PageLoadedInSeconds", pageLoadedInSeconds);
            argumentsOfScenario.Add("PageScrollStep", pageScrollStep);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_10 Navigate to Static Pages", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("Get Static Page URL from AppSetting for {0} and {1}", scenarioName, pageURL_AppSettings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And(string.Format("The Static Page is loaded for browser {0} for device {1}", browser, device), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.When("Accept cookie button is clicked in Static Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then(string.Format("The Static Page loaded with in {0} seconds", pageLoadedInSeconds), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
 testRunner.And("We were able to get Static Page total dimention", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
 testRunner.And("We were able to set the Static Page Screen color mode from AppSetting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
 testRunner.And("Static Page Local storage value for theme \'theme\' is \'dark\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 testRunner.And(string.Format("Take Static Pages page screenshot with name prefix {0}", scenarioName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
 testRunner.And(string.Format("The Static Page is scrolled step by step to end by millisecond delay {0} by {1}", millisecond, pageScrollStep), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 01_chrome-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_01_Chrome_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("01_chrome-GalaxyS5", "chrome", "Galaxy S5", "Niraiya Site Map", "URL:sitemap-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 02_chrome-iPhoneX", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_02_Chrome_IPhoneX()
        {
#line 7
this._04_10NavigateToStaticPages("02_chrome-iPhoneX", "chrome", "iPhone X", "Niraiya Site Map", "URL:sitemap-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 03_chrome-iPad", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_03_Chrome_IPad()
        {
#line 7
this._04_10NavigateToStaticPages("03_chrome-iPad", "chrome", "iPad", "Niraiya Site Map", "URL:sitemap-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 04_chrome-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_04_Chrome_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("04_chrome-Desktop", "chrome", "Desktop", "Niraiya Site Map", "URL:sitemap-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 05_firefox-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_05_Firefox_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("05_firefox-GalaxyS5", "firefox", "Galaxy S5", "Niraiya Site Map", "URL:sitemap-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 06_firefox-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_06_Firefox_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("06_firefox-Desktop", "firefox", "Desktop", "Niraiya Site Map", "URL:sitemap-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 07_chrome-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_07_Chrome_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("07_chrome-GalaxyS5", "chrome", "Galaxy S5", "Niraiya bot", "URL:Niraiyabot-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 08_chrome-iPhoneX", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_08_Chrome_IPhoneX()
        {
#line 7
this._04_10NavigateToStaticPages("08_chrome-iPhoneX", "chrome", "iPhone X", "Niraiya bot", "URL:Niraiyabot-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 09_chrome-iPad", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_09_Chrome_IPad()
        {
#line 7
this._04_10NavigateToStaticPages("09_chrome-iPad", "chrome", "iPad", "Niraiya bot", "URL:Niraiyabot-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 10_chrome-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_10_Chrome_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("10_chrome-Desktop", "chrome", "Desktop", "Niraiya bot", "URL:Niraiyabot-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 11_firefox-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_11_Firefox_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("11_firefox-GalaxyS5", "firefox", "Galaxy S5", "Niraiya bot", "URL:Niraiyabot-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 12_firefox-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_12_Firefox_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("12_firefox-Desktop", "firefox", "Desktop", "Niraiya bot", "URL:Niraiyabot-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 13_chrome-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_13_Chrome_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("13_chrome-GalaxyS5", "chrome", "Galaxy S5", "EmailVerified", "URL:EmailVerified-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 14_chrome-iPhoneX", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_14_Chrome_IPhoneX()
        {
#line 7
this._04_10NavigateToStaticPages("14_chrome-iPhoneX", "chrome", "iPhone X", "EmailVerified", "URL:EmailVerified-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 15_chrome-iPad", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_15_Chrome_IPad()
        {
#line 7
this._04_10NavigateToStaticPages("15_chrome-iPad", "chrome", "iPad", "EmailVerified", "URL:EmailVerified-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 16_chrome-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_16_Chrome_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("16_chrome-Desktop", "chrome", "Desktop", "EmailVerified", "URL:EmailVerified-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 17_firefox-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_17_Firefox_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("17_firefox-GalaxyS5", "firefox", "Galaxy S5", "EmailVerified", "URL:EmailVerified-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 18_firefox-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_18_Firefox_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("18_firefox-Desktop", "firefox", "Desktop", "EmailVerified", "URL:EmailVerified-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 19_chrome-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_19_Chrome_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("19_chrome-GalaxyS5", "chrome", "Galaxy S5", "InValidVerificationId", "URL:InValidVerificationId-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 20_chrome-iPhoneX", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_20_Chrome_IPhoneX()
        {
#line 7
this._04_10NavigateToStaticPages("20_chrome-iPhoneX", "chrome", "iPhone X", "InValidVerificationId", "URL:InValidVerificationId-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 21_chrome-iPad", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_21_Chrome_IPad()
        {
#line 7
this._04_10NavigateToStaticPages("21_chrome-iPad", "chrome", "iPad", "InValidVerificationId", "URL:InValidVerificationId-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 22_chrome-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_22_Chrome_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("22_chrome-Desktop", "chrome", "Desktop", "InValidVerificationId", "URL:InValidVerificationId-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 23_firefox-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_23_Firefox_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("23_firefox-GalaxyS5", "firefox", "Galaxy S5", "InValidVerificationId", "URL:InValidVerificationId-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 24_firefox-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_24_Firefox_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("24_firefox-Desktop", "firefox", "Desktop", "InValidVerificationId", "URL:InValidVerificationId-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 25_chrome-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_25_Chrome_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("25_chrome-GalaxyS5", "chrome", "Galaxy S5", "WebsiteUnderMaintenance", "URL:WebsiteUnderMaintenance-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 26_chrome-iPhoneX", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_26_Chrome_IPhoneX()
        {
#line 7
this._04_10NavigateToStaticPages("26_chrome-iPhoneX", "chrome", "iPhone X", "WebsiteUnderMaintenance", "URL:WebsiteUnderMaintenance-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 27_chrome-iPad", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_27_Chrome_IPad()
        {
#line 7
this._04_10NavigateToStaticPages("27_chrome-iPad", "chrome", "iPad", "WebsiteUnderMaintenance", "URL:WebsiteUnderMaintenance-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 28_chrome-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_28_Chrome_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("28_chrome-Desktop", "chrome", "Desktop", "WebsiteUnderMaintenance", "URL:WebsiteUnderMaintenance-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 29_firefox-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_29_Firefox_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("29_firefox-GalaxyS5", "firefox", "Galaxy S5", "WebsiteUnderMaintenance", "URL:WebsiteUnderMaintenance-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 30_firefox-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_30_Firefox_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("30_firefox-Desktop", "firefox", "Desktop", "WebsiteUnderMaintenance", "URL:WebsiteUnderMaintenance-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 31_chrome-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_31_Chrome_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("31_chrome-GalaxyS5", "chrome", "Galaxy S5", "PageUnderConstruction", "URL:PageUnderConstruction-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 32_chrome-iPhoneX", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_32_Chrome_IPhoneX()
        {
#line 7
this._04_10NavigateToStaticPages("32_chrome-iPhoneX", "chrome", "iPhone X", "PageUnderConstruction", "URL:PageUnderConstruction-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 33_chrome-iPad", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_33_Chrome_IPad()
        {
#line 7
this._04_10NavigateToStaticPages("33_chrome-iPad", "chrome", "iPad", "PageUnderConstruction", "URL:PageUnderConstruction-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 34_chrome-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_34_Chrome_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("34_chrome-Desktop", "chrome", "Desktop", "PageUnderConstruction", "URL:PageUnderConstruction-URL", "500", "10", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 35_firefox-GalaxyS5", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_35_Firefox_GalaxyS5()
        {
#line 7
this._04_10NavigateToStaticPages("35_firefox-GalaxyS5", "firefox", "Galaxy S5", "PageUnderConstruction", "URL:PageUnderConstruction-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_10 Navigate to Static Pages, 36_firefox-Desktop", new string[] {
                "StaticScreens",
                "Parallel"}, SourceLine=19)]
        public virtual void _04_10NavigateToStaticPages_36_Firefox_Desktop()
        {
#line 7
this._04_10NavigateToStaticPages("36_firefox-Desktop", "firefox", "Desktop", "PageUnderConstruction", "URL:PageUnderConstruction-URL", "200", "20", "200", ((string[])(null)));
#line hidden
        }
        
        public virtual void _04_20ValidateToLoadingIndicatorPages(string environment, string browser, string device, string scenarioName, string pageURL_AppSettings, string millisecond, string pageLoadedInSeconds, string pageScrollStep, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Parallel"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Environment", environment);
            argumentsOfScenario.Add("Browser", browser);
            argumentsOfScenario.Add("Device", device);
            argumentsOfScenario.Add("ScenarioName", scenarioName);
            argumentsOfScenario.Add("PageURL-AppSettings", pageURL_AppSettings);
            argumentsOfScenario.Add("Millisecond", millisecond);
            argumentsOfScenario.Add("PageLoadedInSeconds", pageLoadedInSeconds);
            argumentsOfScenario.Add("PageScrollStep", pageScrollStep);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_20 Validate to LoadingIndicator Pages", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 58
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 59
 testRunner.Given(string.Format("Get Static Page URL from AppSetting for {0} and {1}", scenarioName, pageURL_AppSettings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 60
 testRunner.And(string.Format("The Static Page is loaded for browser {0} for device {1}", browser, device), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 61
 testRunner.Then(string.Format("The Static Page loaded with in {0} seconds", pageLoadedInSeconds), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
 testRunner.And("We were able to get Static Page total dimention", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
 testRunner.And("We were able check the LoadingIndicator text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_20 Validate to LoadingIndicator Pages, 01_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=66)]
        public virtual void _04_20ValidateToLoadingIndicatorPages_01_Chrome_GalaxyS5()
        {
#line 58
this._04_20ValidateToLoadingIndicatorPages("01_chrome-GalaxyS5", "chrome", "Galaxy S5", "LoadingIndicator", "URL:LoadingIndicator-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_20 Validate to LoadingIndicator Pages, 02_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=66)]
        public virtual void _04_20ValidateToLoadingIndicatorPages_02_Chrome_IPhoneX()
        {
#line 58
this._04_20ValidateToLoadingIndicatorPages("02_chrome-iPhoneX", "chrome", "iPhone X", "LoadingIndicator", "URL:LoadingIndicator-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_20 Validate to LoadingIndicator Pages, 03_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=66)]
        public virtual void _04_20ValidateToLoadingIndicatorPages_03_Chrome_IPad()
        {
#line 58
this._04_20ValidateToLoadingIndicatorPages("03_chrome-iPad", "chrome", "iPad", "LoadingIndicator", "URL:LoadingIndicator-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_20 Validate to LoadingIndicator Pages, 04_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=66)]
        public virtual void _04_20ValidateToLoadingIndicatorPages_04_Chrome_Desktop()
        {
#line 58
this._04_20ValidateToLoadingIndicatorPages("04_chrome-Desktop", "chrome", "Desktop", "LoadingIndicator", "URL:LoadingIndicator-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_20 Validate to LoadingIndicator Pages, 05_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=66)]
        public virtual void _04_20ValidateToLoadingIndicatorPages_05_Firefox_GalaxyS5()
        {
#line 58
this._04_20ValidateToLoadingIndicatorPages("05_firefox-GalaxyS5", "firefox", "Galaxy S5", "LoadingIndicator", "URL:LoadingIndicator-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_20 Validate to LoadingIndicator Pages, 06_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=66)]
        public virtual void _04_20ValidateToLoadingIndicatorPages_06_Firefox_Desktop()
        {
#line 58
this._04_20ValidateToLoadingIndicatorPages("06_firefox-Desktop", "firefox", "Desktop", "LoadingIndicator", "URL:LoadingIndicator-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        public virtual void _04_30ValidateAjaxErrorPagePage(string environment, string browser, string device, string scenarioName, string pageURL_AppSettings, string millisecond, string pageLoadedInSeconds, string pageScrollStep, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Parallel"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Environment", environment);
            argumentsOfScenario.Add("Browser", browser);
            argumentsOfScenario.Add("Device", device);
            argumentsOfScenario.Add("ScenarioName", scenarioName);
            argumentsOfScenario.Add("PageURL-AppSettings", pageURL_AppSettings);
            argumentsOfScenario.Add("Millisecond", millisecond);
            argumentsOfScenario.Add("PageLoadedInSeconds", pageLoadedInSeconds);
            argumentsOfScenario.Add("PageScrollStep", pageScrollStep);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_30 Validate AjaxErrorPage Page", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 75
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 76
 testRunner.Given(string.Format("Get Static Page URL from AppSetting for {0} and {1}", scenarioName, pageURL_AppSettings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 77
 testRunner.And(string.Format("The Static Page is loaded for browser {0} for device {1}", browser, device), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 78
 testRunner.When("Accept cookie button is clicked in Static Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 79
 testRunner.Then(string.Format("The Static Page loaded with in {0} seconds", pageLoadedInSeconds), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
 testRunner.And("We were able to get Static Page total dimention", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 81
 testRunner.And("We were able to set the Static Page Screen color mode from AppSetting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 82
 testRunner.And("Static Page Local storage value for theme \'theme\' is \'dark\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 83
 testRunner.And("Raise ajax exception at server by clicking \'btnGetAjaxError\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 84
 testRunner.And("Validate AjaxErrorPage Page by popup display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 85
 testRunner.And("Validate Request Id against database log - AjaxErrorPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_30 Validate AjaxErrorPage Page, 01_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=88)]
        public virtual void _04_30ValidateAjaxErrorPagePage_01_Chrome_GalaxyS5()
        {
#line 75
this._04_30ValidateAjaxErrorPagePage("01_chrome-GalaxyS5", "chrome", "Galaxy S5", "AjaxErrorPage", "URL:AjaxErrorPage-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_30 Validate AjaxErrorPage Page, 02_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=88)]
        public virtual void _04_30ValidateAjaxErrorPagePage_02_Chrome_IPhoneX()
        {
#line 75
this._04_30ValidateAjaxErrorPagePage("02_chrome-iPhoneX", "chrome", "iPhone X", "AjaxErrorPage", "URL:AjaxErrorPage-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_30 Validate AjaxErrorPage Page, 03_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=88)]
        public virtual void _04_30ValidateAjaxErrorPagePage_03_Chrome_IPad()
        {
#line 75
this._04_30ValidateAjaxErrorPagePage("03_chrome-iPad", "chrome", "iPad", "AjaxErrorPage", "URL:AjaxErrorPage-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_30 Validate AjaxErrorPage Page, 04_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=88)]
        public virtual void _04_30ValidateAjaxErrorPagePage_04_Chrome_Desktop()
        {
#line 75
this._04_30ValidateAjaxErrorPagePage("04_chrome-Desktop", "chrome", "Desktop", "AjaxErrorPage", "URL:AjaxErrorPage-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_30 Validate AjaxErrorPage Page, 05_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=88)]
        public virtual void _04_30ValidateAjaxErrorPagePage_05_Firefox_GalaxyS5()
        {
#line 75
this._04_30ValidateAjaxErrorPagePage("05_firefox-GalaxyS5", "firefox", "Galaxy S5", "AjaxErrorPage", "URL:AjaxErrorPage-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_30 Validate AjaxErrorPage Page, 06_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=88)]
        public virtual void _04_30ValidateAjaxErrorPagePage_06_Firefox_Desktop()
        {
#line 75
this._04_30ValidateAjaxErrorPagePage("06_firefox-Desktop", "firefox", "Desktop", "AjaxErrorPage", "URL:AjaxErrorPage-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        public virtual void _04_40ValidateErrorPage(string environment, string browser, string device, string scenarioName, string pageURL_AppSettings, string millisecond, string pageLoadedInSeconds, string pageScrollStep, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Parallel"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Environment", environment);
            argumentsOfScenario.Add("Browser", browser);
            argumentsOfScenario.Add("Device", device);
            argumentsOfScenario.Add("ScenarioName", scenarioName);
            argumentsOfScenario.Add("PageURL-AppSettings", pageURL_AppSettings);
            argumentsOfScenario.Add("Millisecond", millisecond);
            argumentsOfScenario.Add("PageLoadedInSeconds", pageLoadedInSeconds);
            argumentsOfScenario.Add("PageScrollStep", pageScrollStep);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_40 Validate Error Page", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 97
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 98
 testRunner.Given(string.Format("Get Static Page URL from AppSetting for {0} and {1}", scenarioName, pageURL_AppSettings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 99
 testRunner.And(string.Format("The Static Page is loaded for browser {0} for device {1}", browser, device), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 100
 testRunner.When("Accept cookie button is clicked in Static Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 101
 testRunner.Then(string.Format("The Static Page loaded with in {0} seconds", pageLoadedInSeconds), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
 testRunner.And("We were able to get Static Page total dimention", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 103
 testRunner.And("We were able to set the Static Page Screen color mode from AppSetting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 104
 testRunner.And("Static Page Local storage value for theme \'theme\' is \'dark\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 105
 testRunner.And("Validate Request Id against database log - ErrorPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_40 Validate Error Page, 01_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=108)]
        public virtual void _04_40ValidateErrorPage_01_Chrome_GalaxyS5()
        {
#line 97
this._04_40ValidateErrorPage("01_chrome-GalaxyS5", "chrome", "Galaxy S5", "ErrorPage", "URL:ErrorPage-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_40 Validate Error Page, 02_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=108)]
        public virtual void _04_40ValidateErrorPage_02_Chrome_IPhoneX()
        {
#line 97
this._04_40ValidateErrorPage("02_chrome-iPhoneX", "chrome", "iPhone X", "ErrorPage", "URL:ErrorPage-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_40 Validate Error Page, 03_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=108)]
        public virtual void _04_40ValidateErrorPage_03_Chrome_IPad()
        {
#line 97
this._04_40ValidateErrorPage("03_chrome-iPad", "chrome", "iPad", "ErrorPage", "URL:ErrorPage-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_40 Validate Error Page, 04_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=108)]
        public virtual void _04_40ValidateErrorPage_04_Chrome_Desktop()
        {
#line 97
this._04_40ValidateErrorPage("04_chrome-Desktop", "chrome", "Desktop", "ErrorPage", "URL:ErrorPage-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_40 Validate Error Page, 05_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=108)]
        public virtual void _04_40ValidateErrorPage_05_Firefox_GalaxyS5()
        {
#line 97
this._04_40ValidateErrorPage("05_firefox-GalaxyS5", "firefox", "Galaxy S5", "ErrorPage", "URL:ErrorPage-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_40 Validate Error Page, 06_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=108)]
        public virtual void _04_40ValidateErrorPage_06_Firefox_Desktop()
        {
#line 97
this._04_40ValidateErrorPage("06_firefox-Desktop", "firefox", "Desktop", "ErrorPage", "URL:ErrorPage-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        public virtual void _04_50ValidateRawHTMLPage1(string environment, string browser, string device, string scenarioName, string pageURL_AppSettings, string millisecond, string pageLoadedInSeconds, string pageScrollStep, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Parallel"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Environment", environment);
            argumentsOfScenario.Add("Browser", browser);
            argumentsOfScenario.Add("Device", device);
            argumentsOfScenario.Add("ScenarioName", scenarioName);
            argumentsOfScenario.Add("PageURL-AppSettings", pageURL_AppSettings);
            argumentsOfScenario.Add("Millisecond", millisecond);
            argumentsOfScenario.Add("PageLoadedInSeconds", pageLoadedInSeconds);
            argumentsOfScenario.Add("PageScrollStep", pageScrollStep);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_50 Validate Raw HTML Page 1", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 117
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 118
 testRunner.Given(string.Format("Get Static Page URL from AppSetting for {0} and {1}", scenarioName, pageURL_AppSettings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 119
 testRunner.And(string.Format("The Static Page is loaded for browser {0} for device {1}", browser, device), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 120
 testRunner.Then(string.Format("The Static Page loaded with in {0} seconds", pageLoadedInSeconds), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 121
 testRunner.And(string.Format("The Static Page is scrolled step by step to end by millisecond delay {0} by {1}", millisecond, pageScrollStep), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 122
 testRunner.And("The Static Page wait for few seconds 2500", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 01_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_01_Chrome_GalaxyS5()
        {
#line 117
this._04_50ValidateRawHTMLPage1("01_chrome-GalaxyS5", "chrome", "Galaxy S5", "sitemap-xml", "URL:sitemapxml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 02_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_02_Chrome_IPhoneX()
        {
#line 117
this._04_50ValidateRawHTMLPage1("02_chrome-iPhoneX", "chrome", "iPhone X", "sitemap-xml", "URL:sitemapxml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 03_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_03_Chrome_IPad()
        {
#line 117
this._04_50ValidateRawHTMLPage1("03_chrome-iPad", "chrome", "iPad", "sitemap-xml", "URL:sitemapxml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 04_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_04_Chrome_Desktop()
        {
#line 117
this._04_50ValidateRawHTMLPage1("04_chrome-Desktop", "chrome", "Desktop", "sitemap-xml", "URL:sitemapxml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 05_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_05_Firefox_GalaxyS5()
        {
#line 117
this._04_50ValidateRawHTMLPage1("05_firefox-GalaxyS5", "firefox", "Galaxy S5", "sitemap-xml", "URL:sitemapxml-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 06_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_06_Firefox_Desktop()
        {
#line 117
this._04_50ValidateRawHTMLPage1("06_firefox-Desktop", "firefox", "Desktop", "sitemap-xml", "URL:sitemapxml-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 07_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_07_Chrome_GalaxyS5()
        {
#line 117
this._04_50ValidateRawHTMLPage1("07_chrome-GalaxyS5", "chrome", "Galaxy S5", "sitemap-blog.xml", "URL:sitemap-blog.xml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 08_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_08_Chrome_IPhoneX()
        {
#line 117
this._04_50ValidateRawHTMLPage1("08_chrome-iPhoneX", "chrome", "iPhone X", "sitemap-blog.xml", "URL:sitemap-blog.xml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 09_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_09_Chrome_IPad()
        {
#line 117
this._04_50ValidateRawHTMLPage1("09_chrome-iPad", "chrome", "iPad", "sitemap-blog.xml", "URL:sitemap-blog.xml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 10_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_10_Chrome_Desktop()
        {
#line 117
this._04_50ValidateRawHTMLPage1("10_chrome-Desktop", "chrome", "Desktop", "sitemap-blog.xml", "URL:sitemap-blog.xml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 11_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_11_Firefox_GalaxyS5()
        {
#line 117
this._04_50ValidateRawHTMLPage1("11_firefox-GalaxyS5", "firefox", "Galaxy S5", "sitemap-blog.xml", "URL:sitemap-blog.xml-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 12_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_12_Firefox_Desktop()
        {
#line 117
this._04_50ValidateRawHTMLPage1("12_firefox-Desktop", "firefox", "Desktop", "sitemap-blog.xml", "URL:sitemap-blog.xml-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 13_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_13_Chrome_GalaxyS5()
        {
#line 117
this._04_50ValidateRawHTMLPage1("13_chrome-GalaxyS5", "chrome", "Galaxy S5", "sitemap-pin.xml", "URL:sitemap-pin.xml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 14_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_14_Chrome_IPhoneX()
        {
#line 117
this._04_50ValidateRawHTMLPage1("14_chrome-iPhoneX", "chrome", "iPhone X", "sitemap-pin.xml", "URL:sitemap-pin.xml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 15_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_15_Chrome_IPad()
        {
#line 117
this._04_50ValidateRawHTMLPage1("15_chrome-iPad", "chrome", "iPad", "sitemap-pin.xml", "URL:sitemap-pin.xml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 16_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_16_Chrome_Desktop()
        {
#line 117
this._04_50ValidateRawHTMLPage1("16_chrome-Desktop", "chrome", "Desktop", "sitemap-pin.xml", "URL:sitemap-pin.xml-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 17_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_17_Firefox_GalaxyS5()
        {
#line 117
this._04_50ValidateRawHTMLPage1("17_firefox-GalaxyS5", "firefox", "Galaxy S5", "sitemap-pin.xml", "URL:sitemap-pin.xml-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_50 Validate Raw HTML Page 1, 18_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=125)]
        public virtual void _04_50ValidateRawHTMLPage1_18_Firefox_Desktop()
        {
#line 117
this._04_50ValidateRawHTMLPage1("18_firefox-Desktop", "firefox", "Desktop", "sitemap-pin.xml", "URL:sitemap-pin.xml-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        public virtual void _04_60ValidateRawHTMLPage2(string environment, string browser, string device, string scenarioName, string pageURL_AppSettings, string millisecond, string pageLoadedInSeconds, string pageScrollStep, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Parallel"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Environment", environment);
            argumentsOfScenario.Add("Browser", browser);
            argumentsOfScenario.Add("Device", device);
            argumentsOfScenario.Add("ScenarioName", scenarioName);
            argumentsOfScenario.Add("PageURL-AppSettings", pageURL_AppSettings);
            argumentsOfScenario.Add("Millisecond", millisecond);
            argumentsOfScenario.Add("PageLoadedInSeconds", pageLoadedInSeconds);
            argumentsOfScenario.Add("PageScrollStep", pageScrollStep);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_60 Validate Raw HTML Page 2", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 146
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 147
 testRunner.Given(string.Format("Get Static Page URL from AppSetting for {0} and {1}", scenarioName, pageURL_AppSettings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 148
 testRunner.And(string.Format("The Static Page is loaded for browser {0} for device {1}", browser, device), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 149
 testRunner.Then(string.Format("The Static Page loaded with in {0} seconds", pageLoadedInSeconds), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 150
 testRunner.And(string.Format("The Static Page is scrolled step by step to end by millisecond delay {0} by {1}", millisecond, pageScrollStep), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 151
 testRunner.And("The Static Page wait for few seconds 2500", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 01_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_01_Chrome_GalaxyS5()
        {
#line 146
this._04_60ValidateRawHTMLPage2("01_chrome-GalaxyS5", "chrome", "Galaxy S5", "robots.txt", "URL:robots.txt-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 02_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_02_Chrome_IPhoneX()
        {
#line 146
this._04_60ValidateRawHTMLPage2("02_chrome-iPhoneX", "chrome", "iPhone X", "robots.txt", "URL:robots.txt-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 03_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_03_Chrome_IPad()
        {
#line 146
this._04_60ValidateRawHTMLPage2("03_chrome-iPad", "chrome", "iPad", "robots.txt", "URL:robots.txt-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 04_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_04_Chrome_Desktop()
        {
#line 146
this._04_60ValidateRawHTMLPage2("04_chrome-Desktop", "chrome", "Desktop", "robots.txt", "URL:robots.txt-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 05_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_05_Firefox_GalaxyS5()
        {
#line 146
this._04_60ValidateRawHTMLPage2("05_firefox-GalaxyS5", "firefox", "Galaxy S5", "robots.txt", "URL:robots.txt-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 06_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_06_Firefox_Desktop()
        {
#line 146
this._04_60ValidateRawHTMLPage2("06_firefox-Desktop", "firefox", "Desktop", "robots.txt", "URL:robots.txt-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 07_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_07_Chrome_GalaxyS5()
        {
#line 146
this._04_60ValidateRawHTMLPage2("07_chrome-GalaxyS5", "chrome", "Galaxy S5", "SitemapUrls", "URL:SitemapUrls-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 08_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_08_Chrome_IPhoneX()
        {
#line 146
this._04_60ValidateRawHTMLPage2("08_chrome-iPhoneX", "chrome", "iPhone X", "SitemapUrls", "URL:SitemapUrls-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 09_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_09_Chrome_IPad()
        {
#line 146
this._04_60ValidateRawHTMLPage2("09_chrome-iPad", "chrome", "iPad", "SitemapUrls", "URL:SitemapUrls-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 10_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_10_Chrome_Desktop()
        {
#line 146
this._04_60ValidateRawHTMLPage2("10_chrome-Desktop", "chrome", "Desktop", "SitemapUrls", "URL:SitemapUrls-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 11_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_11_Firefox_GalaxyS5()
        {
#line 146
this._04_60ValidateRawHTMLPage2("11_firefox-GalaxyS5", "firefox", "Galaxy S5", "SitemapUrls", "URL:SitemapUrls-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 12_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_12_Firefox_Desktop()
        {
#line 146
this._04_60ValidateRawHTMLPage2("12_firefox-Desktop", "firefox", "Desktop", "SitemapUrls", "URL:SitemapUrls-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 13_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_13_Chrome_GalaxyS5()
        {
#line 146
this._04_60ValidateRawHTMLPage2("13_chrome-GalaxyS5", "chrome", "Galaxy S5", "rss", "URL:rss-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 14_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_14_Chrome_IPhoneX()
        {
#line 146
this._04_60ValidateRawHTMLPage2("14_chrome-iPhoneX", "chrome", "iPhone X", "rss", "URL:rss-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 15_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_15_Chrome_IPad()
        {
#line 146
this._04_60ValidateRawHTMLPage2("15_chrome-iPad", "chrome", "iPad", "rss", "URL:rss-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 16_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_16_Chrome_Desktop()
        {
#line 146
this._04_60ValidateRawHTMLPage2("16_chrome-Desktop", "chrome", "Desktop", "rss", "URL:rss-URL", "500", "10", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 17_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_17_Firefox_GalaxyS5()
        {
#line 146
this._04_60ValidateRawHTMLPage2("17_firefox-GalaxyS5", "firefox", "Galaxy S5", "rss", "URL:rss-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_60 Validate Raw HTML Page 2, 18_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=154)]
        public virtual void _04_60ValidateRawHTMLPage2_18_Firefox_Desktop()
        {
#line 146
this._04_60ValidateRawHTMLPage2("18_firefox-Desktop", "firefox", "Desktop", "rss", "URL:rss-URL", "200", "20", "500", ((string[])(null)));
#line hidden
        }
        
        public virtual void _04_70ValidateRawHTMLPage3(string environment, string browser, string device, string scenarioName, string pageURL_AppSettings, string millisecond, string pageLoadedInSeconds, string pageScrollStep, string waitFor, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Parallel"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Environment", environment);
            argumentsOfScenario.Add("Browser", browser);
            argumentsOfScenario.Add("Device", device);
            argumentsOfScenario.Add("ScenarioName", scenarioName);
            argumentsOfScenario.Add("PageURL-AppSettings", pageURL_AppSettings);
            argumentsOfScenario.Add("Millisecond", millisecond);
            argumentsOfScenario.Add("PageLoadedInSeconds", pageLoadedInSeconds);
            argumentsOfScenario.Add("PageScrollStep", pageScrollStep);
            argumentsOfScenario.Add("WaitFor", waitFor);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_70 Validate Raw HTML Page 3", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 175
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 176
 testRunner.Given(string.Format("Get Static Page URL from AppSetting for {0} and {1}", scenarioName, pageURL_AppSettings), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 177
 testRunner.And(string.Format("The Static Page is loaded for browser {0} for device {1}", browser, device), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 178
 testRunner.Then(string.Format("The Static Page loaded with in {0} seconds", pageLoadedInSeconds), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 179
 testRunner.And(string.Format("The Static Page is scrolled step by step to end by millisecond delay {0} by {1}", millisecond, pageScrollStep), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 180
 testRunner.And(string.Format("The Static Page wait for few seconds {0}", waitFor), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 01_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_01_Chrome_GalaxyS5()
        {
#line 175
this._04_70ValidateRawHTMLPage3("01_chrome-GalaxyS5", "chrome", "Galaxy S5", "GetNiraiyaAdDisplayStatus", "URLStatic:GetNiraiyaAdDisplayStatus-URL", "500", "10", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 02_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_02_Chrome_IPhoneX()
        {
#line 175
this._04_70ValidateRawHTMLPage3("02_chrome-iPhoneX", "chrome", "iPhone X", "GetNiraiyaAdDisplayStatus", "URLStatic:GetNiraiyaAdDisplayStatus-URL", "500", "10", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 03_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_03_Chrome_IPad()
        {
#line 175
this._04_70ValidateRawHTMLPage3("03_chrome-iPad", "chrome", "iPad", "GetNiraiyaAdDisplayStatus", "URLStatic:GetNiraiyaAdDisplayStatus-URL", "500", "10", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 04_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_04_Chrome_Desktop()
        {
#line 175
this._04_70ValidateRawHTMLPage3("04_chrome-Desktop", "chrome", "Desktop", "GetNiraiyaAdDisplayStatus", "URLStatic:GetNiraiyaAdDisplayStatus-URL", "500", "10", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 05_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_05_Firefox_GalaxyS5()
        {
#line 175
this._04_70ValidateRawHTMLPage3("05_firefox-GalaxyS5", "firefox", "Galaxy S5", "GetNiraiyaAdDisplayStatus", "URLStatic:GetNiraiyaAdDisplayStatus-URL", "200", "20", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 06_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_06_Firefox_Desktop()
        {
#line 175
this._04_70ValidateRawHTMLPage3("06_firefox-Desktop", "firefox", "Desktop", "GetNiraiyaAdDisplayStatus", "URLStatic:GetNiraiyaAdDisplayStatus-URL", "200", "20", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 07_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_07_Chrome_GalaxyS5()
        {
#line 175
this._04_70ValidateRawHTMLPage3("07_chrome-GalaxyS5", "chrome", "Galaxy S5", "GetNiraiyaJobsStatus", "URLStatic:GetNiraiyaJobsStatus-URL", "500", "10", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 08_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_08_Chrome_IPhoneX()
        {
#line 175
this._04_70ValidateRawHTMLPage3("08_chrome-iPhoneX", "chrome", "iPhone X", "GetNiraiyaJobsStatus", "URLStatic:GetNiraiyaJobsStatus-URL", "500", "10", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 09_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_09_Chrome_IPad()
        {
#line 175
this._04_70ValidateRawHTMLPage3("09_chrome-iPad", "chrome", "iPad", "GetNiraiyaJobsStatus", "URLStatic:GetNiraiyaJobsStatus-URL", "500", "10", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 10_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_10_Chrome_Desktop()
        {
#line 175
this._04_70ValidateRawHTMLPage3("10_chrome-Desktop", "chrome", "Desktop", "GetNiraiyaJobsStatus", "URLStatic:GetNiraiyaJobsStatus-URL", "500", "10", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 11_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_11_Firefox_GalaxyS5()
        {
#line 175
this._04_70ValidateRawHTMLPage3("11_firefox-GalaxyS5", "firefox", "Galaxy S5", "GetNiraiyaJobsStatus", "URLStatic:GetNiraiyaJobsStatus-URL", "200", "20", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 12_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_12_Firefox_Desktop()
        {
#line 175
this._04_70ValidateRawHTMLPage3("12_firefox-Desktop", "firefox", "Desktop", "GetNiraiyaJobsStatus", "URLStatic:GetNiraiyaJobsStatus-URL", "200", "20", "500", "2500", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 13_chrome-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_13_Chrome_GalaxyS5()
        {
#line 175
this._04_70ValidateRawHTMLPage3("13_chrome-GalaxyS5", "chrome", "Galaxy S5", "Elmah", "URLStatic:Elmah-URL", "500", "10", "500", "8000", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 14_chrome-iPhoneX", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_14_Chrome_IPhoneX()
        {
#line 175
this._04_70ValidateRawHTMLPage3("14_chrome-iPhoneX", "chrome", "iPhone X", "Elmah", "URLStatic:Elmah-URL", "500", "10", "500", "8000", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 15_chrome-iPad", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_15_Chrome_IPad()
        {
#line 175
this._04_70ValidateRawHTMLPage3("15_chrome-iPad", "chrome", "iPad", "Elmah", "URLStatic:Elmah-URL", "500", "10", "500", "8000", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 16_chrome-Desktop", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_16_Chrome_Desktop()
        {
#line 175
this._04_70ValidateRawHTMLPage3("16_chrome-Desktop", "chrome", "Desktop", "Elmah", "URLStatic:Elmah-URL", "500", "10", "500", "8000", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 17_firefox-GalaxyS5", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_17_Firefox_GalaxyS5()
        {
#line 175
this._04_70ValidateRawHTMLPage3("17_firefox-GalaxyS5", "firefox", "Galaxy S5", "Elmah", "URLStatic:Elmah-URL", "200", "20", "500", "8000", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("04_70 Validate Raw HTML Page 3, 18_firefox-Desktop", new string[] {
                "Parallel"}, SourceLine=183)]
        public virtual void _04_70ValidateRawHTMLPage3_18_Firefox_Desktop()
        {
#line 175
this._04_70ValidateRawHTMLPage3("18_firefox-Desktop", "firefox", "Desktop", "Elmah", "URLStatic:Elmah-URL", "200", "20", "500", "8000", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
